# Configuración de seguridad para DuocPoint
# Este archivo contiene configuraciones de seguridad para la aplicación

# Configuración de validación de archivos
file_validation:
  max_file_size: 10485760  # 10MB en bytes
  allowed_extensions: [".pdf", ".jpg", ".jpeg", ".png", ".gif"]
  scan_for_malware: true
  quarantine_suspicious: true

# Configuración de rate limiting
rate_limiting:
  requests_per_minute: 60
  requests_per_hour: 1000
  requests_per_day: 10000
  burst_limit: 10

# Configuración de autenticación
authentication:
  max_login_attempts: 5
  lockout_duration: 900  # 15 minutos en segundos
  password_min_length: 8
  require_special_chars: true
  require_numbers: true
  require_uppercase: true

# Configuración de sesiones
session:
  timeout: 3600  # 1 hora en segundos
  secure_cookies: true
  http_only_cookies: true
  same_site: "Lax"

# Configuración de CORS
cors:
  allowed_origins: ["http://localhost:8000", "http://127.0.0.1:8000"]
  allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allowed_headers: ["Content-Type", "Authorization", "X-CSRFToken"]
  allow_credentials: true

# Configuración de logging de seguridad
security_logging:
  log_failed_logins: true
  log_suspicious_activity: true
  log_file_access: true
  log_admin_actions: true

# Configuración de backup
backup:
  enabled: true
  frequency: "daily"
  retention_days: 30
  encrypt_backups: true

# Configuración de monitoreo
monitoring:
  enable_intrusion_detection: true
  alert_on_suspicious_activity: true
  log_all_requests: false
  performance_monitoring: true
