# Configuración de seguridad 
file_validation: 
  max_file_size: 10485760 
  allowed_extensions: [".pdf", ".jpg", ".jpeg", ".png", ".gif"] 
rate_limiting: 
  requests_per_minute: 60 
  requests_per_hour: 1000 
authentication: 
  max_login_attempts: 5 
  lockout_duration: 900 
